### ISSUE TITLE
Xcode 10.2 and swift 5.0

### ISSUE THREAD

**Issue by Romaric13** [Orange-OpenSource/orange-trust-badge-ios#23]
Hi,
I'm working with Unity 2018.4.2 and I've integrated Orange Trust badge iOS. My Xcode version is 10.2 and I've used pod for Orange Trust Badge integration. I've compilation error in OrangeTrustBadge-Swift.h line 250 with the Enum : "The error is Too many arguments provided to function-like macro invocation". I can't succeed building my project with the plugin. Is this a Swift 5.0 integration problem ?
Thanks
Romaric

**Comment by marcbeaudoin** [comment]
Version 1.1.5 is available and compatible with Xcode 10.2.1/Swift 5.0
